apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
spec:
  storageClassName: slow
  volumeName: mysql-persistent-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
