apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql # Hostname expected by Wordpress image by default
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql


