apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mysql
    app: mysql
    tier: db
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mysql
  strategy: {}
  template:
    metadata:
      labels:
        run: mysql
        app: mysql
    spec:
      volumes:
      - name: mysql-pv-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-storage
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        image: mysql:5.7
        name: mysql
        args:
          - "--ignore-db-dir=lost+found"
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-pv-storage


